Name:           perl-Term-Shell
Version:        0.09
Release:        1%{?dist}
Summary:        Simple command-line shell framework
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Term-Shell/
Source0:        http://www.cpan.org/authors/id/S/SH/SHLOMIF/Term-Shell-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.008
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Getopt::Long) >= 2.36
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Term::ReadKey)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::Autoformat)
Requires:       perl(Data::Dumper)
Requires:       perl(File::Temp)
Requires:       perl(Getopt::Long) >= 2.36
Requires:       perl(Term::ReadKey)
Requires:       perl(Text::Autoformat)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Term::Shell lets you write simple command-line shells. All the boring
details like command-line parsing, terminal handling, and tab completion
are handled for you.

%prep
%setup -q -n Term-Shell-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini examples LICENSE META.json README scripts weaver.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Wed Aug 29 2018 Rolli, Michael (ID) 0.09-1
- Specfile autogenerated by cpanspec 1.78.
